# Generated by Django 5.0.4 on 2024-04-17 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adres',
            fields=[
                ('ID_adresu', models.AutoField(primary_key=True, serialize=False)),
                ('Kraj', models.CharField(max_length=100)),
                ('Miasto', models.CharField(max_length=100)),
                ('Kod_pocztowy', models.CharField(max_length=20)),
                ('Ulica', models.CharField(max_length=255)),
                ('Numer_domu', models.CharField(max_length=10)),
                ('Numer_mieszkania', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nieruchomosc',
            fields=[
                ('ID_nieruchomosci', models.AutoField(primary_key=True, serialize=False)),
                ('Powierzchnia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Liczba_pokoi', models.IntegerField()),
                ('Cena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Status', models.CharField(max_length=50)),
                ('Typ_nieruchomosci', models.CharField(max_length=50)),
                ('Opis', models.TextField(blank=True)),
                ('ID_adresu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.adres')),
            ],
        ),
        migrations.CreateModel(
            name='Najemca',
            fields=[
                ('ID_najemcy', models.AutoField(primary_key=True, serialize=False)),
                ('Imie', models.CharField(max_length=100)),
                ('Nazwisko', models.CharField(max_length=100)),
                ('Telefon', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=100)),
                ('Data_rozpoczecia_najmu', models.DateField(blank=True, null=True)),
                ('Data_zakonczenia_najmu', models.DateField(blank=True, null=True)),
                ('ID_nieruchomosci', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.nieruchomosc')),
            ],
        ),
        migrations.CreateModel(
            name='UmowaNajmu',
            fields=[
                ('ID_umowy', models.AutoField(primary_key=True, serialize=False)),
                ('Data_rozpoczecia', models.DateField()),
                ('Data_zakonczenia', models.DateField()),
                ('Oplata_miesieczna', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Kaucja', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Status', models.CharField(max_length=50)),
                ('ID_najemcy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.najemca')),
                ('ID_nieruchomosci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.nieruchomosc')),
            ],
        ),
        migrations.CreateModel(
            name='Oplata',
            fields=[
                ('ID_oplaty', models.AutoField(primary_key=True, serialize=False)),
                ('Data_platnosci', models.DateField()),
                ('Kwota', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Typ_oplaty', models.CharField(max_length=50)),
                ('ID_umowy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.umowanajmu')),
            ],
        ),
        migrations.CreateModel(
            name='Zdjecie',
            fields=[
                ('ID_zdjecia', models.AutoField(primary_key=True, serialize=False)),
                ('Obraz', models.ImageField(upload_to='zdjecia_nieruchomosci')),
                ('ID_nieruchomosci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.nieruchomosc')),
            ],
        ),
    ]
