# Generated by Django 5.0.4 on 2024-04-17 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nieruchomosc',
            name='ID_adresu',
            field=models.ForeignKey(db_column='ID_adresu', on_delete=django.db.models.deletion.CASCADE, to='listings.adres'),
        ),
        migrations.AlterModelTable(
            name='adres',
            table='adresy',
        ),
        migrations.AlterModelTable(
            name='najemca',
            table='Najemcy',
        ),
        migrations.AlterModelTable(
            name='nieruchomosc',
            table='Nieruchomosci',
        ),
        migrations.AlterModelTable(
            name='oplata',
            table='Oplaty',
        ),
        migrations.AlterModelTable(
            name='umowanajmu',
            table='Umowy_najmu',
        ),
        migrations.AlterModelTable(
            name='zdjecie',
            table='Zdjecia',
        ),
    ]
